# application.yml

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vamsigoud.vamsi123@gmail.com
    password: password123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false